// ===========================ORGANIZATIONS===========================

export const FETCH_ORG_LIST__SUCCESS = 'FETCH_ORG_LIST__SUCCESS';
export const FETCH_ORG_LIST__REQUEST = 'FETCH_ORG_LIST__REQUEST';
export const FETCH_ORG_LIST__FAILURE = 'FETCH_ORG_LIST__FAILURE';

export const FETCH_ORG_DATA__SUCCESS = 'FETCH_ORG_DATA__SUCCESS';
export const FETCH_ORG_DATA__REQUEST = 'FETCH_ORG_DATA__REQUEST';
export const FETCH_ORG_DATA__FAILURE = 'FETCH_ORG_DATA__FAILURE';

// ===========================CLIENTS===========================

export const FETCH_CLIENT_LIST__SUCCESS = 'FETCH_CLIENT_LIST__SUCCESS';
export const FETCH_CLIENT_LIST__REQUEST = 'FETCH_CLIENT_LIST__REQUEST';
export const FETCH_CLIENT_LIST__FAILURE = 'FETCH_CLIENT_LIST__FAILURE';

export const FETCH_CLIENT_LIST_FOR_ORG__SUCCESS =
  'FETCH_CLIENT_LIST_FOR_ORG__SUCCESS';
export const FETCH_CLIENT_LIST_FOR_ORG__REQUEST =
  'FETCH_CLIENT_LIST_FOR_ORG__REQUEST';
export const FETCH_CLIENT_LIST_FOR_ORG__FAILURE =
  'FETCH_CLIENT_LIST_FOR_ORG__FAILURE';

export const FETCH_CLIENT_DATA__SUCCESS = 'FETCH_CLIENT_DATA__SUCCESS';
export const FETCH_CLIENT_DATA__REQUEST = 'FETCH_CLIENT_DATA__REQUEST';
export const FETCH_CLIENT_DATA__FAILURE = 'FETCH_CLIENT_DATA__FAILURE';

// ===========================LOANS===========================

export const FETCH_LOAN_DATA__SUCCESS = 'FETCH_LOAN_DATA__SUCCESS';
export const FETCH_LOAN_DATA__REQUEST = 'FETCH_LOAN_DATA__REQUEST';
export const FETCH_LOAN_DATA__FAILURE = 'FETCH_LOAN_DATA__FAILURE';

// ===========================PROPOSALS===========================

export const FETCH_PROPOSALS__SUCCESS = 'FETCH_PROPOSALS__SUCCESS';
export const FETCH_PROPOSALS__REQUEST = 'FETCH_PROPOSALS__REQUEST';
export const FETCH_PROPOSALS__FAILURE = 'FETCH_PROPOSALS__FAILURE';
