// ===========================ORGANIZATIONS===========================

export const FETCH_ORG_LIST__SUCCESS = 'FETCH_ORG_LIST__SUCCESS';
export const FETCH_ORG_LIST__REQUEST = 'FETCH_ORG_LIST__REQUEST';
export const FETCH_ORG_LIST__FAILURE = 'FETCH_ORG_LIST__FAILURE';

export const FETCH_ORG_DATA__SUCCESS = 'FETCH_ORG_DATA__SUCCESS';
export const FETCH_ORG_DATA__REQUEST = 'FETCH_ORG_DATA__REQUEST';
export const FETCH_ORG_DATA__FAILURE = 'FETCH_ORG_DATA__FAILURE';

export const CREATE_ORG__SUCCESS = 'CREATE_ORG__SUCCESS';
export const CREATE_ORG__REQUEST = 'CREATE_ORG__REQUEST';
export const CREATE_ORG__FAILURE = 'CREATE_ORG__FAILURE';

// ===========================CLIENTS===========================

export const FETCH_CLIENT_LIST__SUCCESS = 'FETCH_CLIENT_LIST__SUCCESS';
export const FETCH_CLIENT_LIST__REQUEST = 'FETCH_CLIENT_LIST__REQUEST';
export const FETCH_CLIENT_LIST__FAILURE = 'FETCH_CLIENT_LIST__FAILURE';

export const FETCH_CLIENT_LIST_FOR_ORG__SUCCESS =
  'FETCH_CLIENT_LIST_FOR_ORG__SUCCESS';
export const FETCH_CLIENT_LIST_FOR_ORG__REQUEST =
  'FETCH_CLIENT_LIST_FOR_ORG__REQUEST';
export const FETCH_CLIENT_LIST_FOR_ORG__FAILURE =
  'FETCH_CLIENT_LIST_FOR_ORG__FAILURE';

export const FETCH_CLIENT_DATA__SUCCESS = 'FETCH_CLIENT_DATA__SUCCESS';
export const FETCH_CLIENT_DATA__REQUEST = 'FETCH_CLIENT_DATA__REQUEST';
export const FETCH_CLIENT_DATA__FAILURE = 'FETCH_CLIENT_DATA__FAILURE';

export const CREATE_CLIENT__SUCCESS = 'CREATE_CLIENT__SUCCESS';
export const CREATE_CLIENT__REQUEST = 'CREATE_CLIENT__REQUEST';
export const CREATE_CLIENT__FAILURE = 'CREATE_CLIENT__FAILURE';

// ===========================LOANS===========================

export const FETCH_LOAN_DATA__SUCCESS = 'FETCH_LOAN_DATA__SUCCESS';
export const FETCH_LOAN_DATA__REQUEST = 'FETCH_LOAN_DATA__REQUEST';
export const FETCH_LOAN_DATA__FAILURE = 'FETCH_LOAN_DATA__FAILURE';

// ===========================PROPOSALS===========================

export const FETCH_PROPOSALS__SUCCESS = 'FETCH_PROPOSALS__SUCCESS';
export const FETCH_PROPOSALS__REQUEST = 'FETCH_PROPOSALS__REQUEST';
export const FETCH_PROPOSALS__FAILURE = 'FETCH_PROPOSALS__FAILURE';

export const INCREASE_VOTE__SUCCESS = 'INCREASE_VOTE__SUCCESS';
export const INCREASE_VOTE__REQUEST = 'INCREASE_VOTE__REQUEST';
export const INCREASE_VOTE__FAILURE = 'INCREASE_VOTE__FAILURE';

export const DECREASE_VOTE__SUCCESS = 'DECREASE_VOTE__SUCCESS';
export const DECREASE_VOTE__REQUEST = 'DECREASE_VOTE__REQUEST';
export const DECREASE_VOTE__FAILURE = 'DECREASE_VOTE__FAILURE';
